[package]
name = "logwatcher"
version = "0.1.1"
authors = ["Kaan Karakaya"]
edition = "2018"
description = "A lib to watch log files for new Changes, just like tail -f"

readme = "README.md"
keywords = ["log", "watcher", "tail"]
license = "MIT/Apache-2.0"

[dependencies]
flate2 = "1.0"
